### ISSUE TITLE
Second level domain

### ISSUE THREAD

**Issue by erichuang2015** [mikikg/whois_checher#1]
Hello

it is now return only TLD and Domain from string such as .com .net ..
how to recognize both  google.co.in and google.in

**Comment by mikikg** [comment]
Hi @erichuang2015, I just pushed small changes with a fix for the name extraction from FQDN.
For any additional TLDs you need to add appropriate WHOIS server address into script `whois-server.php`, for example:
```
'in'  => 'whois.registry.in',
```
For the full list of TLDs/Whois servers see http://www.iana.org/domains/root/db/
